### ISSUE TITLE
Incompatible with node 15.11.0

### ISSUE THREAD

**Issue by evrins** [YunYouJun/nnrm#1]
install with `yarn global add nnrm`

➜  ~ yarn global add nnrm
yarn global v1.22.10
warning package.json: No license field
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
**error nnrm@0.0.4: The engine "node" is incompatible with this module. Expected version "14.x". Got "15.11.0"**
error Found incompatible module.
info Visit https://yarnpkg.com/en/docs/cli/global for documentation about this command.

**Comment by YunYouJun** [comment]
Fixed by modifying packages.json `engines.node`. hhh Released in v0.0.5.

**Comment by evrins** [comment]
Working fine on node 15.11.0 with 0.0.5
