### ISSUE TITLE
:bug: `TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined`

### ISSUE THREAD

**Issue by Adkinsm2020** [YunYouJun/nnrm#3]
![图片](https://user-images.githubusercontent.com/75924586/135611063-7de316f8-15e9-4bd9-9918-5c7581ca1fd5.png)

node `16.5.0`

OS `Win11 22000.194`

**Comment by Adkinsm2020** [comment]
![图片](https://user-images.githubusercontent.com/75924586/135612031-18eed880-a2f8-46fa-9f15-8b0b3b75df6a.png)

使用git bash 后无任何反应

**Comment by YunYouJun** [comment]
`nnrm` 本身是没有反应的，试试 `nnrm -h`。

**Comment by YunYouJun** [comment]
报错是输入什么情况下出现的？

**Comment by Adkinsm2020** [comment]
正常情况啊

**Comment by Adkinsm2020** [comment]
> 
> 
> ![图片](https://user-images.githubusercontent.com/75924586/135611063-7de316f8-15e9-4bd9-9918-5c7581ca1fd5.png)
> 
> node `16.5.0`
> 
> OS `Win11 22000.194`

好的，已解决，是因为我用cmd执行的
