### ISSUE TITLE
yrm切换yarn的源时没有生效

### ISSUE THREAD

**Issue by JobinJia** [YunYouJun/nnrm#9]
感谢作者的帮助，这个很好使，但是我在使用中发现一个小问题：

环境： 
   macOS: 
node version:
   v17.4.0
yarn version:
   v1.22.17
nnrm version:
  index.js/0.3.5 darwin-x64 node-v17.4.0

操作如下
<img width="460" alt="image" src="https://user-images.githubusercontent.com/9244703/161184265-3051c1ba-5c8e-4633-991c-4d52fb060f5b.png">

通过yrm use 切换源之后，执行yrm get config registry 发现并没有更新: (

**Comment by YunYouJun** [comment]
Released in `v0.3.6`.
